### ISSUE TITLE
Ideas for more funtionality

### ISSUE THREAD

**Issue by staraxis** [felixsteghofer/homeassistant_custom_components#2]
I really like this custom component, would be great if it could be an official HA component in the future.
I have an idea on how to integrate PTZ into the component:

The Shinobi API allows for control of the PTZ of a camera using this `http://xxx.xxx.xxx.xxx/[API KEY]/control/[GROUP KEY]/[MONITOR ID]/[ACTION]` where `[ACTION]` is the control you want to execute e.g. left, right etc.

A way to integrate this would be to have those actions as HA events. Users would then have to create scripts to execute these actions - this could be displayed nicely in the new Lovelace UI with entity-buttons.

```
sequence:
- event: cam_ptz
    event_data:
    entity_id: device_tracker.paulus
    event_id: left
```
I don't code so this is an idea that may be terrible! Thanks for reading.

Also I think motion as a `binary_sensor` would be great!
