### ISSUE TITLE
TypeError: __init__() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by timelf123** [felixsteghofer/homeassistant_custom_components#3]
`TypeError: __init__() takes 2 positional arguments but 3 were given`

```
shinobi:
  host: 192.168.x.y:8080
  api_key: zxy
  group_key: asdf
  ssl: false

camera:
  - platform: shinobi
    whitelist: 
      - cam_android
```
