### ISSUE TITLE
The following components and platforms could not be set up - home assistant v0.91.4

### ISSUE THREAD

**Issue by aristosv** [felixsteghofer/homeassistant_custom_components#5]
I copied the whole custom_components/ folder in Home Assistant's config folder
I added the below in configuration.yaml and restarted home assistant.

```
shinobi:
  host: 192.168.23:8080
  api_key: xxyDJ6jgqhodSBsuut1EzPsZvsvdsC1QHJe
  group_key: 1WyMdsvcdsvdsEoZY1W
```

I got a message saying:

```
The following components and platforms could not be set up:
shinobi
Please check your config
```

In the logs, it says:

```
Log Details (ERROR)
Mon Apr 22 2019 08:10:30 GMT+0300 (Eastern European Summer Time)
Setup failed for shinobi: Component failed to initialize.
```

I removed ":8080" from host: and restarted home assistant again.

Again I got a message saying:

```
The following components and platforms could not be set up:
shinobi
Please check your config
```

I am using home assistant v0.91.4
I'm I doing something wrong?

Thanks
